#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
usage: blobtools <command> [<args>...] [--help]

commands:
  create    create a BlobDB
  view      print BlobDB
  plot      plot BlobDB as a blobplot

  bam2cov   generate cov file from bam file

-h --help    show this

"""

from __future__ import division
import sys
from subprocess import call
from os.path import join, dirname
from docopt import docopt

if __name__ == '__main__':
    main_dir = join(dirname(__file__), '')
    args = docopt(__doc__,
                  version='version 0.9.6',
                  options_first=True)
    #print(args)

    argv = [args['<command>']] + args['<args>']
    if args['<command>'] == 'create':
        exit(call(['python', main_dir + 'create.py'] + argv))
    elif args['<command>'] == 'view':
        exit(call(['python', main_dir + 'view.py'] + argv))
    elif args['<command>'] == 'plot':
        exit(call(['python', main_dir + 'plot.py'] + argv))
    elif args['<command>'] == 'bam2cov':
        exit(call(['python', main_dir + 'bam2cov.py'] + argv))
    else:
        exit("%r is not a blobtools command. See 'blobtools -h'." % args['<command>'])