#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
usage: blobtools.py <command> [<args>...] [--help]

commands:
  forge     create a BlobDb
  view      print BlobDB to screen
  plot      plot BlobDB as a blobplot

-h --help    show this

"""

from __future__ import division
import sys
from subprocess import call
from os.path import join, dirname
from docopt import docopt

if __name__ == '__main__':
    main_dir = join(dirname(__file__), '')
    args = docopt(__doc__,
                  version='version 0.1',
                  options_first=True)
    #print(args)

    argv = [args['<command>']] + args['<args>']
    if args['<command>'] == 'forge':
        exit(call(['python', main_dir + 'forge.py'] + argv))
    elif args['<command>'] == 'view':
        exit(call(['python', main_dir + 'view.py'] + argv))
    elif args['<command>'] == 'plot':
        exit(call(['python', main_dir + 'plot.py'] + argv))
    else:
        exit("%r is not a blobtools command. See 'blobtools -h'." % args['<command>'])